create table "public"."profiles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user" uuid,
    "name" text
);


create table "public"."user_exercises" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "exercise" bigint,
    "workout" bigint
);


create table "public"."workouts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user" uuid,
    "name" text,
    "day" text,
    "targetMuscleGroup" text
);


alter table "public"."exercises" add column "equipmentRequired" text;

alter table "public"."exercises" add column "exerciseType" text;

alter table "public"."exercises" add column "experienceLevel" text;

alter table "public"."exercises" add column "forceType" text;

alter table "public"."exercises" add column "mechanics" text;

alter table "public"."exercises" add column "name" text;

alter table "public"."exercises" add column "secondaryMuscles" text;

alter table "public"."exercises" add column "videoId" text;

alter table "public"."exercises" disable row level security;

CREATE UNIQUE INDEX exercises_name_key ON public.exercises USING btree (name);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX user_exercises_pkey ON public.user_exercises USING btree (id);

CREATE UNIQUE INDEX workouts_pkey ON public.workouts USING btree (id);

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."user_exercises" add constraint "user_exercises_pkey" PRIMARY KEY using index "user_exercises_pkey";

alter table "public"."workouts" add constraint "workouts_pkey" PRIMARY KEY using index "workouts_pkey";

alter table "public"."exercises" add constraint "exercises_name_key" UNIQUE using index "exercises_name_key";

alter table "public"."profiles" add constraint "profiles_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_user_fkey";

alter table "public"."user_exercises" add constraint "user_exercises_exercise_fkey" FOREIGN KEY (exercise) REFERENCES exercises(id) not valid;

alter table "public"."user_exercises" validate constraint "user_exercises_exercise_fkey";

alter table "public"."user_exercises" add constraint "user_exercises_workout_fkey" FOREIGN KEY (workout) REFERENCES workouts(id) not valid;

alter table "public"."user_exercises" validate constraint "user_exercises_workout_fkey";

alter table "public"."workouts" add constraint "workouts_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) not valid;

alter table "public"."workouts" validate constraint "workouts_user_fkey";


